$ErrorActionPreference = "Stop"

$RepoUrl = "https://github.com/p8n-ai/jira-skills"
$EnvFile = Join-Path $HOME ".jira-skills.env.ps1"

function Write-Section([string]$Message) {
    Write-Host ""
    Write-Host $Message
}

function Test-Command([string]$Name) {
    return $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ask-YesNo([string]$Prompt, [bool]$DefaultYes = $true) {
    $suffix = if ($DefaultYes) { "[Y/n]" } else { "[y/N]" }
    $reply = Read-Host "$Prompt $suffix"
    if ([string]::IsNullOrWhiteSpace($reply)) {
        return $DefaultYes
    }
    return $reply -match '^[Yy]$'
}

function Install-Skills {
    Write-Section "Installing Jira skills from $RepoUrl"

    if (-not (Test-Command "npx")) {
        Write-Error "npx was not found. Install Node.js first, then rerun this installer. Download: https://nodejs.org/"
    }

    & npx -y skills add $RepoUrl
    if ($LASTEXITCODE -ne 0) {
        throw "skills installation failed"
    }
}

function Install-JiraCli {
    if (Test-Command "jira") {
        Write-Section "jira CLI is already installed: $((Get-Command jira).Source)"
        return
    }

    if (-not (Ask-YesNo "jira CLI is required for these skills. Install it now?" $true)) {
        Write-Warning "Skipping jira CLI installation. Install it later and run: jira init"
        return
    }

    if (Test-Command "scoop") {
        Write-Section "Installing jira CLI with Scoop..."
        try {
            & scoop bucket add extras
        } catch {
            Write-Warning "Could not add extras bucket, continuing..."
        }
        & scoop install jira-cli
        if ($LASTEXITCODE -ne 0) {
            throw "scoop install jira-cli failed"
        }
    } elseif (Test-Command "winget") {
        Write-Warning "jira-cli is commonly installed on Windows with Scoop. Winget may not provide this package."
        Write-Host "Install Scoop from https://scoop.sh/, then run: scoop bucket add extras; scoop install jira-cli"
    } else {
        Write-Warning "No supported package manager found. Install jira CLI manually:"
        Write-Host "https://github.com/ankitpokhrel/jira-cli/wiki/Installation"
    }
}

function Configure-JiraCli {
    if (-not (Test-Command "jira")) {
        return
    }

    if (Ask-YesNo "Run 'jira init' now to configure the Jira CLI account?" $true) {
        & jira init
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "jira init did not complete successfully. You can rerun it later with: jira init"
        }
    }
}

function Read-SecretText([string]$Prompt) {
    $secure = Read-Host $Prompt -AsSecureString
    if ($secure.Length -eq 0) {
        return ""
    }

    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
}

function Set-UserEnvIfPresent([string]$Name, [string]$Value) {
    if (-not [string]::IsNullOrWhiteSpace($Value)) {
        [Environment]::SetEnvironmentVariable($Name, $Value, "User")
        Set-Item -Path "Env:$Name" -Value $Value
    }
}

function Write-EnvFile {
    Write-Section "Configure environment variables for attachment downloads."
    Write-Host "These are optional for most jira CLI commands, but required by attachment helpers."
    Write-Host "Leave a value blank to skip it."

    $baseUrl = Read-Host "Jira base URL, for example https://jira.example.com"
    $email = Read-Host "Jira email"
    $token = Read-SecretText "Jira API token, input hidden"

    New-Item -ItemType Directory -Force -Path (Split-Path $EnvFile) | Out-Null

    $lines = @(
        "# Jira skills environment",
        "# Generated by $RepoUrl/install.ps1"
    )

    if (-not [string]::IsNullOrWhiteSpace($baseUrl)) { $lines += "`$env:JIRA_BASE_URL = '$($baseUrl.Replace("'", "''"))'" }
    if (-not [string]::IsNullOrWhiteSpace($email)) { $lines += "`$env:JIRA_EMAIL = '$($email.Replace("'", "''"))'" }
    if (-not [string]::IsNullOrWhiteSpace($token)) { $lines += "`$env:JIRA_API_TOKEN = '$($token.Replace("'", "''"))'" }

    Set-Content -Path $EnvFile -Value $lines -Encoding UTF8
    Write-Section "Saved environment file: $EnvFile"

    Set-UserEnvIfPresent "JIRA_BASE_URL" $baseUrl
    Set-UserEnvIfPresent "JIRA_EMAIL" $email
    Set-UserEnvIfPresent "JIRA_API_TOKEN" $token

    if ($PROFILE) {
        $profileDir = Split-Path $PROFILE
        New-Item -ItemType Directory -Force -Path $profileDir | Out-Null
        if (-not (Test-Path $PROFILE)) {
            New-Item -ItemType File -Path $PROFILE | Out-Null
        }

        $sourceLine = ". `"$EnvFile`""
        $profileText = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
        if ($profileText -notlike "*$sourceLine*") {
            Add-Content -Path $PROFILE -Value ""
            Add-Content -Path $PROFILE -Value "# Jira skills environment"
            Add-Content -Path $PROFILE -Value $sourceLine
            Write-Host "Updated PowerShell profile: $PROFILE"
        }
    }

    Write-Host "Environment variables were saved as user-level environment variables and will persist for new PowerShell sessions and device restarts."
    . $EnvFile
}

function Main {
    Write-Section "Jira Skills Installer"
    Install-Skills
    Install-JiraCli
    Configure-JiraCli

    if (Ask-YesNo "Set Jira skills environment variables now?" $true) {
        Write-EnvFile
    }

    Write-Section "Installation complete."
    Write-Host "Open a new PowerShell window, or run: . `"$EnvFile`""
    Write-Host "Then try: jira me"
}

Main
