#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://github.com/p8n-ai/jira-skills"
ENV_FILE="${HOME}/.jira-skills.env"

say() { printf '\n%s\n' "$*"; }
warn() { printf '\nWarning: %s\n' "$*" >&2; }
err() { printf '\nError: %s\n' "$*" >&2; }

has_cmd() { command -v "$1" >/dev/null 2>&1; }

ask_yes_no() {
  local prompt="$1"
  local default="${2:-y}"
  local suffix="[Y/n]"
  [[ "$default" == "n" ]] && suffix="[y/N]"

  local reply
  read -r -p "$prompt $suffix " reply || true
  reply="${reply:-$default}"
  [[ "$reply" =~ ^[Yy]$ ]]
}

append_source_line() {
  local profile="$1"
  local source_line="[ -f \"$ENV_FILE\" ] && . \"$ENV_FILE\""

  mkdir -p "$(dirname "$profile")"
  touch "$profile"
  if ! grep -Fq "$source_line" "$profile"; then
    {
      echo ""
      echo "# Jira skills environment"
      echo "$source_line"
    } >> "$profile"
    echo "Updated shell profile: $profile"
  fi
}

install_skills() {
  say "Installing Jira skills from $REPO_URL"

  if ! has_cmd npx; then
    err "npx was not found. Install Node.js first, then rerun this installer."
    echo "Node.js download: https://nodejs.org/"
    exit 1
  fi

  npx -y skills add "$REPO_URL"
}

install_jira_cli() {
  if has_cmd jira; then
    say "jira CLI is already installed: $(command -v jira)"
    return
  fi

  if ! ask_yes_no "jira CLI is required for these skills. Install it now?" "y"; then
    warn "Skipping jira CLI installation. Install it later and run: jira init"
    return
  fi

  local os
  os="$(uname -s 2>/dev/null || echo unknown)"

  if [[ "$os" == "Darwin" ]] && has_cmd brew; then
    say "Installing jira CLI with Homebrew..."
    brew install ankitpokhrel/jira-cli/jira-cli
  elif has_cmd brew; then
    say "Installing jira CLI with Homebrew..."
    brew install ankitpokhrel/jira-cli/jira-cli
  elif has_cmd go; then
    say "Installing jira CLI with Go..."
    go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest
    warn "If jira is still not on PATH, add your Go bin directory, usually \$HOME/go/bin."
  else
    warn "No supported package manager found. Install jira CLI manually:"
    echo "https://github.com/ankitpokhrel/jira-cli/wiki/Installation"
    return
  fi
}

configure_jira_cli() {
  if ! has_cmd jira; then
    return
  fi

  if ask_yes_no "Run 'jira init' now to configure the Jira CLI account?" "y"; then
    jira init || warn "jira init did not complete successfully. You can rerun it later with: jira init"
  fi
}

write_env_file() {
  say "Configure environment variables for attachment downloads."
  echo "These are optional for most jira CLI commands, but required by attachment helpers."
  echo "Leave a value blank to skip it."

  local base_url=""
  local email=""
  local token=""

  read -r -p "Jira base URL, for example https://jira.example.com: " base_url || true
  read -r -p "Jira email: " email || true
  read -r -s -p "Jira API token, input hidden: " token || true
  printf '\n'

  mkdir -p "$(dirname "$ENV_FILE")"
  umask 077
  {
    echo "# Jira skills environment"
    echo "# Generated by $REPO_URL/install.sh"
    [[ -n "$base_url" ]] && printf 'export JIRA_BASE_URL=%q\n' "$base_url"
    [[ -n "$email" ]] && printf 'export JIRA_EMAIL=%q\n' "$email"
    [[ -n "$token" ]] && printf 'export JIRA_API_TOKEN=%q\n' "$token"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"

  say "Saved environment file: $ENV_FILE"

  # Persist for future terminals. We update the detected shell profile plus common
  # Bash/Zsh startup files so the variables survive terminal and device restarts.
  local shell_name="$(basename "${SHELL:-}")"
  case "$shell_name" in
    zsh) append_source_line "${HOME}/.zshrc" ;;
    bash) append_source_line "${HOME}/.bashrc" ;;
    fish)
      warn "Fish shell detected. Please source $ENV_FILE manually or translate exports into fish syntax."
      ;;
  esac

  # Also update common POSIX shell profiles when present or when no shell was detected.
  append_source_line "${HOME}/.profile"
  if [[ "$shell_name" == "bash" || -f "${HOME}/.bash_profile" ]]; then
    append_source_line "${HOME}/.bash_profile"
  fi

  echo "Environment variables are persistent for new shell sessions."

  # Make variables available to child processes spawned by this installer.
  # They cannot be exported back into the already-running parent shell.
  # shellcheck disable=SC1090
  . "$ENV_FILE"
}

main() {
  say "Jira Skills Installer"
  install_skills
  install_jira_cli
  configure_jira_cli

  if ask_yes_no "Set Jira skills environment variables now?" "y"; then
    write_env_file
  fi

  say "Installation complete."
  echo "Open a new terminal, or run: source \"$ENV_FILE\""
  echo "Then try: jira me"
}

main "$@"
